name: Label

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: conventional-labels
        uses: DonBLong/conventional-labels@v0.0.0
        with:
          map: |
            feat: enhancement, feature
            perf: enhancement, performance
            fix: bug, fix
            docs: documentation
